# SPDX-FileCopyrightText: 2025 Brady Fomegne and contributors
#
# SPDX-License-Identifier: MPL-2.0

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[info]
name = "Fe始fe始"
country_code = "cm"
writing_systems = ["gacl"]
afrim_data = ["fmp"]

[info.short]
source = "https://en.wikipedia.org/wiki/Fe%CA%BCfe%CA%BC_language"
en = "Southern Bantoid language spoken in Cameroon"

[info.description]
source = "https://en.wikipedia.org/wiki/Fe%CA%BCfe%CA%BC_language"
en = "Fe始fe始 is a member of the Bamileke group of the Eastern Grassfields branch of the South Bantoid language family. It is spoken by about 140,000 people in the Haut-Nkam (Upper Nkam) Department in the West Region in the southwest of Cameroon, particularly around the town of Bafang."
