# SPDX-FileCopyrightText: 2025 Brady Fomegne and contributors
#
# SPDX-License-Identifier: MPL-2.0

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[info]
name = "Bamun"
languages = ["cm-bax"]
script_type = "syllabary"
country_code = "cm"

[info.description]
source = "https://en.wikipedia.org/wiki/Bamum_script"
en = "The Bamum scripts are an evolutionary series of six scripts created for the Bamum language by Ibrahim Njoya, King of Bamum (now western Cameroon). They are notable for evolving from a pictographic system to a semi-syllabary in the space of fourteen years, from 1896 to 1910. Bamum type was cast in 1918, but the script fell into disuse around 1931. A project began around 2007 to revive the Bamum script."
