# SPDX-FileCopyrightText: 2025 Brady Fomegne and contributors
#
# SPDX-License-Identifier: MPL-2.0

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[info]
name = "GACL"
languages = ["cm-fmp", "cm-ewo"]
script_type = "latin"
country_code = "cm"

[info.description]
source = "https://en.wikipedia.org/wiki/General_Alphabet_of_Cameroon_Languages"
en = "The General Alphabet of Cameroon Languages is an orthographic system created in the late 1970s for all Cameroonian languages. Consonant and vowel letters are not to contain diacritics, though ⟨ẅ⟩ is a temporary exception. The alphabet is not used sufficiently for the one unique letter, a bilabial trill, to have been added to Unicode; in any case, that letter has now been replaced."

[layout]
row0 = ["q", "w", "e", "ɛ", "r", "t", "y", "u", "i", "o", "ɔ", "p"]
row1 = ["a", "s", "d", "ɗ", "f", "g", "h", "j", "k", "l", "ŋ"]
row2 = ["z", "x", "c", "v", "b", "ɓ", "n", "ɲ", "m"]
