# SPDX-FileCopyrightText: 2025 Brady Fomegne and contributors
#
# SPDX-License-Identifier: MPL-2.0

name: CI lint
on:
  workflow_dispatch:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff djlint scancode-toolkit 
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: |
          ruff format --check lewa
          ruff check --output-format=github lewa
      - name: Run Djlint
        run: |
          djlint --lint lewa
          djlint --check lewa
      - name: Run scancode-toolkit
        run: |
          scancode -n `nproc` --json-pp - --license --copyright .
      - name: Run REUSE
        run: |
          reuse lint
